# Common Makefile between Z1 and Z1SP

CONTIKI_TARGET_SOURCEFILES += contiki-z1-platform.c 
CLEAN += *.z1-dw1000 obj_z1

include $(CONTIKI)/platform/z1-dw1000/Makefile.common

ifeq ($(ZOLERTIA_Z1SP),1)
include $(CONTIKI)/platform/z1-dw1000/Makefile.z1sp
endif

MODULES += core/net \
           core/net/mac core/net/mac/contikimac \
           core/net/llsec \
           dev/sht11 dev/dw1000 dev/cc2420
