MOTELIST_ZOLERTIA = remote-dw1000

BOARD_SOURCEFILES += dw1000-zoul-arch.c dw1000.c dw1000-util.c dw1000-driver.c
BOARD_SOURCEFILES += board.c antenna-sw.c mmc-arch.c rtcc.c leds-res-arch.c power-mgmt.c
MODULES += lib/fs/fat lib/fs/fat/option platform/zoul/fs/fat dev/disk/mmc
