CONTIKI = ../../../../../..
CONTIKI_PROJECT = node
CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

CONTIKI_WITH_RIME = 1
MODULES += core/net/mac/tsch
MODULES += examples/zolertia/zoul/dw1000/testbed

all: $(CONTIKI_PROJECT)

include $(CONTIKI)/Makefile.include
